package models

import "runtime"

var goos = runtime.GOOS

var DefaultTargetsWindows = map[string]string{
	"claude":       "~/AppData/Roaming/Claude/skills/",
	"codex":        "~/.codex/skills/",
	"copilot":      "~/.copilot/skills/",
	"cursor":       "~/.cursor/skills/",
	"gemini":       "~/.gemini/skills/",
	"goose":        "~/AppData/Roaming/goose/skills/",
	"opencode":     "~/AppData/Roaming/opencode/skills/",
	"roo":          "~/.roo/skills/",
	"trae":         "~/.trae/skills/",
	"windsurf":     "~/.windsurf/skills/",
	"amp":          "~/.amp/skills/",
	"agents":       "~/.agents/skills/",
	"aider":        "~/.aider-desk/skills/",
	"augment":      "~/.augment/skills/",
	"bob":          "~/.bob/skills/",
	"codearts":     "~/.codeartsdoer/skills/",
	"codebuddy":    "~/.codebuddy/skills/",
	"codemaker":    "~/.codemaker/skills/",
	"codestudio":   "~/.codestudio/skills/",
	"commandcode":  "~/.commandcode/skills/",
	"continue":     "~/.continue/skills/",
	"cortex":       "~/.snowflake/cortex/skills/",
	"crush":        "~/AppData/Roaming/crush/skills/",
	"deepagents":   "~/.deepagents/agent/skills/",
	"devin":        "~/AppData/Roaming/devin/skills/",
	"dexto":        "~/.dexto/",
	"droid":        "~/.factory/skills/",
	"firebender":   "~/.firebender/skills/",
	"forgecode":    "~/.forge/skills/",
	"hermes":       "~/.hermes/skills/",
	"junie":        "~/.junie/skills/",
	"iflow":        "~/.iflow/skills/",
	"kilo":         "~/.kilocode/skills/",
	"kimi":         "~/AppData/Roaming/agents/skills/",
	"kiro":         "~/.kiro/skills/",
	"kode":         "~/.kode/skills/",
	"mcpjam":       "~/.mcpjam/skills/",
	"vibe":         "~/.vibe/skills/",
	"mux":          "~/.mux/skills/",
	"openhands":    "~/.openhands/skills/",
	"pi":           "~/.pi/agent/skills/",
	"qoder":        "~/.qoder/skills/",
	"qwen":         "~/.qwen/skills/",
	"rovodev":      "~/.rovodev/skills/",
	"tabnine":      "~/.tabnine/agent/skills/",
	"trae-cn":      "~/.trae-cn/skills/",
	"warp":         "~/.warp/",
	"zencoder":     "~/.zencoder/skills/",
	"neovate":      "~/.neovate/skills/",
	"pochi":        "~/.pochi/skills/",
	"adal":         "~/.adal/skills/",
	"antigravity":  "~/.gemini/antigravity/skills/",
}

var DefaultTargetsUnix = map[string]string{
	"claude":       "~/.claude/skills/",
	"codex":        "~/.codex/skills/",
	"copilot":      "~/.copilot/skills/",
	"cursor":       "~/.cursor/skills/",
	"gemini":       "~/.gemini/skills/",
	"goose":        "~/.config/goose/skills/",
	"opencode":     "~/.config/opencode/skills/",
	"roo":          "~/.roo/skills/",
	"trae":         "~/.trae/skills/",
	"windsurf":     "~/.windsurf/skills/",
	"amp":          "~/.amp/skills/",
	"agents":       "~/.agents/skills/",
	"aider":        "~/.aider-desk/skills/",
	"augment":      "~/.augment/skills/",
	"bob":          "~/.bob/skills/",
	"codearts":     "~/.codeartsdoer/skills/",
	"codebuddy":    "~/.codebuddy/skills/",
	"codemaker":    "~/.codemaker/skills/",
	"codestudio":   "~/.codestudio/skills/",
	"commandcode":  "~/.commandcode/skills/",
	"continue":     "~/.continue/skills/",
	"cortex":       "~/.snowflake/cortex/skills/",
	"crush":        "~/.config/crush/skills/",
	"deepagents":   "~/.deepagents/agent/skills/",
	"devin":        "~/.config/devin/skills/",
	"dexto":        "~/.dexto/",
	"droid":        "~/.factory/skills/",
	"firebender":   "~/.firebender/skills/",
	"forgecode":    "~/.forge/skills/",
	"hermes":       "~/.hermes/skills/",
	"junie":        "~/.junie/skills/",
	"iflow":        "~/.iflow/skills/",
	"kilo":         "~/.kilocode/skills/",
	"kimi":         "~/.config/agents/skills/",
	"kiro":         "~/.kiro/skills/",
	"kode":         "~/.kode/skills/",
	"mcpjam":       "~/.mcpjam/skills/",
	"vibe":         "~/.vibe/skills/",
	"mux":          "~/.mux/skills/",
	"openhands":    "~/.openhands/skills/",
	"pi":           "~/.pi/agent/skills/",
	"qoder":        "~/.qoder/skills/",
	"qwen":         "~/.qwen/skills/",
	"rovodev":      "~/.rovodev/skills/",
	"tabnine":      "~/.tabnine/agent/skills/",
	"trae-cn":      "~/.trae-cn/skills/",
	"warp":         "~/.warp/",
	"zencoder":     "~/.zencoder/skills/",
	"neovate":      "~/.neovate/skills/",
	"pochi":        "~/.pochi/skills/",
	"adal":         "~/.adal/skills/",
	"antigravity":  "~/.gemini/antigravity/skills/",
}

func GetDefaultTargets() map[string]string {
	if goos == "windows" {
		return DefaultTargetsWindows
	}
	return DefaultTargetsUnix
}

type Config struct {
	Targets         map[string]string `json:"targets"`
	DefaultTemplate *string           `json:"default_template"`
}
